apache/openwhisk-apigateway

api-gateway-config/scripts/lua/lib/filemgmt.lua

~~Added `Access-Control-Allow-Methods: *` response header.~~
Replaced wildcard with explicit verbs.
Removed `Access-Control-Allow-Origin: *` and `Access-Control-Allow-Credentials: true` headers because they already exist. @mhamann @DavidMGreen PTAL

Modify cors response headers

---

api-gateway-config/scripts/lua/lib/utils.lua
api-gateway-config/scripts/lua/management.lua

* Fixed bug where managedUrl was returning an extra slash at the end when the basepath is set to `/`
* modified uuid randomseed to use `os.clock` which uses milliseconds, rather than `os.time` which uses seconds.
@mhamann @lostinthestory PTAL

Fix managed url with basepath

---

Dockerfile
api-gateway-config/conf.d/management_apis.conf
api-gateway-config/scripts/lua/lib/filemgmt.lua
api-gateway-config/scripts/lua/lib/logger.lua
api-gateway-config/scripts/lua/lib/redis.lua
api-gateway-config/scripts/lua/lib/request.lua
api-gateway-config/scripts/lua/management.lua
api-gateway-config/tests/run-tests.sh
api-gateway-config/tests/spec/test.lua
init.sh

@mhamann @lostinthestory @DavidMGreen PTAL.
- Added `resourceKeys` redis [set](http://redis.io/commands/SET), which stores all of the `resources:*:*` keys. This set is used to sync with redis, rather than using the `keys("*")` command. Has been tested with 2000+ APIs. Fixes #14 and fixes #24.
- Implemented [coroutines](http://lua-users.org/wiki/CoroutinesTutorial), to run redis sync and subscribe "simultaneously" on startup (actually passing control back and forth between the coroutines). This prevents the sync process from blocking the subscribe process (or vice versa) when the gateway starts up.

Redis sync

---

api-gateway-config/conf.d/management_apis.conf
api-gateway-config/scripts/lua/lib/redis.lua
api-gateway-config/scripts/lua/management.lua

Added `/v1/health-check`, which checks the status of gateway sync with redis. Returns 503 if sync is still in progress, 200 if finished. Closes #27. @mhamann @lostinthestory @DavidMGreen PTAL.

Implement health check for gateway sync

---

api-gateway-config/conf.d/management_apis.conf
api-gateway-config/scripts/lua/lib/logger.lua
api-gateway-config/scripts/lua/lib/redis.lua
api-gateway-config/scripts/lua/management.lua
init.sh

Closes #40. Tail all logs in `/var/log/api-gateway/` to stdout. Also send previous stdout logs to `management.log` (changed from `mgmt_error.log`). @lostinthestory @mhamann PTAL.

Tail logs to stdout

---

.gitignore
.travis.yml
README.md
api-gateway-config/scripts/lua/routing.lua
api-gateway-config/tests/install-deps.sh
api-gateway-config/tests/run-tests.sh
api-gateway-config/tests/scripts/lua/lib/logger.lua
api-gateway-config/tests/scripts/lua/lib/redis.lua
api-gateway-config/tests/scripts/lua/lib/request.lua
api-gateway-config/tests/scripts/lua/lib/utils.lua
api-gateway-config/tests/scripts/lua/routing.lua
api-gateway-config/tests/set_paths.lua

Fixes #82 and #80.
1) Due to bad regex handling, the gateway wasn't able to proxy properly to the backend (#82). Based on discussion with @mhamann and @codymwalker, modified `routing.lua` to find the correct redis key based on the number of slashes in basePath + resourcePath
2) Updated how path parameter is handled with the new design
3) Also fixed the cases where the resource path is just a single "/" (#80)
@mhamann @codymwalker @DavidMGreen PTAL

Redis routing fix for backend proxy

---

README.md
api-gateway-config/scripts/lua/policies/security/clientSecret.lua
doc/policies.md

Updated travis build status link in README to reflect the new name change to `openwhisk-apigateway`. Closes #79

Update build status in README

---

api-gateway-config/scripts/lua/routing.lua

Fixes additional issue related to #82. This fixes a bug where if the the gatewayPath that's passed in is longer than what's currently stored in redis for that tenant, the routing doesn't work properly. 
@mhamann @cmwalker PTAL

Fix proxy routing issue

---

api-gateway-config/scripts/lua/routing.lua

Fixes #98. The problem was that lua treats hyphens (`-`) as special characters, so we have to escape it. @codymwalker PTAL

Handle hyphens for incoming proxy uri

---

api-gateway-config/scripts/lua/lib/redis.lua

Fixes #105. @codymwalker @mhamann 
Increased the `scan` count to 10,000 (default is 10), which dramatically reduced the response time. Below are the results from my lua profiler for an API invoke, with around ~100,000 keys in redis:
Before:
```
| TOTAL TIME = 2.323872
| FILE                                              : FUNCTION                                : LINE                : TIME        : RELATIVE    : CALLED      |
| /etc/api-gateway/scripts/lua/lib/redis.lua        : getAllResourceKeys                      :  218                : 2.317       : 99.72%      :       1     |
| /usr/local/api-gateway/lualib/resty/redis.lua     : scan                                    :  166                : 1.111       : 47.82%      :   10575     |
| /usr/local/api-gateway/lualib/resty/redis.lua …
```

Increase count for redis scan

---

conf.d/managed_endpoints.conf
scripts/lua/management/apis.lua
scripts/lua/policies/backendRouting.lua
scripts/lua/policies/mapping.lua
scripts/lua/routing.lua

Closes #86. @codymwalker @mhamann PTAL.
Added `backendRouting` policy. You define it as follows inside the policies array:
```
"policies": [{
"type": "backendRouting",
"value": {
"header": "x-backend-test-header",
"whitelist": ["httpbin.org"]
}
},
...
]
```
- The `header` field is optional. If not defined, it defaults to `X-Cf-Forwarded-Url` for cf route services.
- When you invoke this API, you will have to set the `header` (in this example, `x-backend-test-header`) with a new backendUrl as its value
- `whitelist` is an array of allowed hosts that can be used for the new backendUrl value

Add dynamic backend routing

---

conf.d/api_gateway_logging.conf
conf.d/managed_endpoints.conf
scripts/lua/cors.lua
scripts/lua/lib/redis.lua
scripts/lua/management/apis.lua
scripts/lua/management/resources.lua
scripts/lua/routing.lua
tests/scripts/lua/lib/redis.lua

Fixes #127 @mhamann @codymwalker PTAL
`access.log` now logs additional `tenantNamespace` and `tenantInstance` fields.

Add tenant namespace and instance to api doc

---

.travis.yml
Makefile
README.md
scripts/lua/lib/redis.lua
scripts/lua/management/lib/resources.lua
scripts/lua/management/routes/apis.lua

Fixes #107. @mhamann @codymwalker PTAL
When an API is created, a `resources:<tenantId>:__index__` set is created and all resource keys associated with that API is added to this set. This way, when a resource of that API is invoked, it first looks up that `resources:<tenantId>:__index__` set and performs the lookup algorithm on just the resources in that set. This prevents scanning through the entire redis database.
The same change of creating `resources:<tenantId>:__index__` and adding resource keys to this set  has to be implemented for the cloud case as well. @gclyne Can you take a look at adding this to your component?

Improve efficiency of getting resources

---

scripts/lua/routing.lua

@codymwalker PTAL
`gsub` is global substitution, meaning that it will replace all instances of the pattern in the string. I've modified it to use `find` to get the start and end index of the first occurrence of the pattern, and then take the substring after that pattern.

Fix analytics logging

---

conf.d/managed_endpoints.conf
scripts/lua/cors.lua
scripts/lua/routing.lua

@mhamann @codymwalker @taylorking PTAL
Updated the routing logic to return the appropriate CORS response headers for `options` preflight requests as well as for the actual requests.

Add cors preflight logic

---

conf.d/api_gateway_logging.conf
conf.d/managed_endpoints.conf
conf.d/management_apis.conf
scripts/lua/routing.lua

Fixes #173 @mhamann @codymwalker PTAL
Changes:
* To see the `requestHeaders`, `requestBody`, `responseHeaders`, and `responseBody` in the access logs, invoke the API with the `X-Debug-Mode` header
* Appended query parameters to cf analytics uri that's being logged
* Disabled logging for health check because it was cluttering up the logs

Add support for X-Debug-Mode header

---

scripts/lua/policies/security/clientSecret.lua

Fixes #171. @codymwalker @mhamann PTAL 
The problem was that `ngx.var.apiKey` was getting set in the `apiKey` security policy but not in the `clientSecret` policy

Add api key to access log with client secret enabled

---

Dockerfile

Fixes #180. @mhamann @codymwalker PTAL
The docker container now starts up with `dumb-init` and can respond to signals, such as ctrl-c to shut down the container, ctrl-z to suspend it, etc.

Use dumb-init to handle signals properly

---

conf.d/management_apis.conf
doc/policies.md
scripts/lua/lib/utils.lua
scripts/lua/management/lib/subscriptions.lua
scripts/lua/management/lib/swagger.lua
scripts/lua/management/routes/subscriptions.lua
scripts/lua/policies/security/clientSecret.lua
tests/scripts/lua/lib/subscriptions.lua
tests/scripts/lua/management/examples/example1.json
tests/scripts/lua/management/examples/example2.json
tests/scripts/lua/management/lib/swagger.lua

Fixes #104. Fixes #72. @mhamann @codymwalker PTAL
* Added new v2 API for managing subscriptions (client id and client secret)
- POST /v2/{tenant_id}/subscriptions
```
{
artifact_id: *(string),
client_id: *(string),
client_secret: (string)
}
```
- GET /v2/{tenant_id}/subscriptions?artifact_id={artifact_id}
- DELETE /v2/{tenant_id}/subscriptions/{client_id}?artifact_id={artifact_id}
* Updated OpenAPI doc parse logic to handle client secret security policy

Add subscriptions api for v2 interface

---

scripts/lua/policies/mapping.lua

Fixed checking for an empty `body` table.

Fix empty body check in request mapping

---

scripts/lua/oauth/github.lua
scripts/lua/oauth/google.lua
scripts/lua/policies/security/oauth2.lua

I was calling redis.close twice which sometimes can fail if the second call happens after redis is already closed.

remove redis.close causing intermittent failures

---

tools/travis/build.sh

This reverts commit ddea5c9095f3798305320181247abafa41b7abc1.
@mhamann or @houshengbo could you review and merge this.
Closes #233

Revert "Remove the CLI gradle build in Travis CI (#232)"

---

tools/travis/build.sh

The travis build fails because a Gradle action in the testing portion of 'tools/travis/build.sh' refers to the no-longer-existing swift 3 action.  This patch removes that reference and corrects a lint warning while it's at it.
I have an Apache CLA in place.

Remove Swift3 reference from Travis build

---

scripts/lua/routing.lua

@mhamann 
Lua's `string.gfind` function is deprecated and has been and renamed to `string.gmatch`

Use gmatch instead of gfind

---

Dockerfile
README.md
build_config_supervisor.sh
conf.d/includes/basic_endpoints.conf
init.sh

This PR introduces the capability for the Gateway to sync its configuration with a remote folder in the cloud such as Amazon S3, Google Cloud Storage, IBM Cloud Object Storage, Dropbox, and [many others](https://rclone.org/). The configuration is monitored for changes, and when a file is changed, the Gateway is reloaded automatically. This is very useful to gracefully update the Gateway on the fly, without impacting the active traffic; if the new configuration is invalid, the Gateway doesn't break, running with the last known valid configuration.
See the updated README for more details.
Other changes:
```javascript
{
"lua_version": "LuaJIT 2.1.0-beta3",
"status": "API-Gateway is running",
"config": {
"lastChangeDetected": "2018-04-24T20:44:59.6466131Z",
"lastReload": …
```

Sync the Gateway configuration with a remote location

---

Dockerfile
api-gateway.conf
conf.d/api_gateway_init.conf
conf.d/api_gateway_logging.conf
conf.d/blacklist.conf
conf.d/commons/common-headers.conf
conf.d/default.conf
conf.d/includes/analytics_endpoints.conf
conf.d/includes/basic_endpoints.conf
html/index.html
tests/test_initialization.t
tools/travis/setup.sh

This issue relates to #288.
Changes:

updated some licenses to ASF and removed naxsi module

---

scripts/lua/cors.lua
tests/fakengx.lua
tests/scripts/lua/cors.lua

- Fix 'Access-Control-Allow-Headers` header getting removed
- Do not modify cors headers when cors is not set in the config
- Strip all cors headers if cors is set to false in the config

Fix Access-Control-Allow-Headers header; Fix case when cors is not set

---

conf.d/managed_endpoints.conf

* Update proxy timeout for managed APIs to accommodate Whisk invokers returning a 202 shortly after 60s.
Currently, the Whisk invokers timeout after 60s and return a 202 with the activation ID. However, the gateway has a default read timeout of 60s, meaning that it hangs up just before the invoker returns the 202. This change allows the gateway to receive the 202 response.
@mhamann @alexsong93 PTAL

Update managed API timeout

---

Dockerfile
scripts/lua/routing.lua

Fixes issue where empty JSON arrays were getting converted to empty objects.
See https://github.com/openresty/lua-cjson#decode_array_with_array_mt.
@mhamann

Decode empty JSON arrays correctly

---

tools/travis/build.sh

package rename for whisk.core is now org.apache.openwhisk.core

---

scripts/lua/management/lib/tenants.lua

This fix adds paging to the v2 getTenantAPIs api by honoring the skip and limit paramaters, if present in the request. This is to address issue #1692 in incubator-openwhisk.

Add paging to getTenantAPIs

---

scripts/lua/management/lib/tenants.lua

Proposed fix for #342.
@larandersson if you can take a look at the suggested patch it would be appreciated 🙏. The `nil` checks were not sufficient since the values for limit and skip are the string `"undefined"`.

Guard against missing query parameters.

---

.travis.yml
Dockerfile
Dockerfile.test.unit
Makefile

This PR primarily moves the gateway unit test runs into their own docker container in order to make it easier to test locally. You can now avoid installing Lua and various deps onto your local machine and simply run `make test` to run all of the available units.
I also converted the main Dockerfile into a multi-stage build, which drastically improves build times for subsequent builds. A few syntax fixes are included as well, as Docker was throwing some warnings during builds.

Run test framework in a Docker container

---

conf.d/commons/common-headers.conf
scripts/lua/routing.lua

- Set `X-Forwarded-Host` based on upstream headers. If header is present in the request, it will honor the value coming from upstream.
- Override the `request_uri` portion of `X-Forwarded-Url`, if `X-Forwarded-Uri` is present in upstream request.

Add support for preserving XF headers from upstream

---

conf.d/managed_endpoints.conf

Fixes https://github.com/apache/openwhisk-apigateway/issues/364

Fix max body size limit

---

conf.d/managed_endpoints.conf

fix(http): Use HTTP 1.1 for upstreams

---

README.md
scripts/lua/policies/backendRouting.lua
tests/scripts/lua/policies/backendRouting.lua

Connects to #362 
This change will ignore `/api/<tenant>` when matching the original URI and computing the backend URI. 
- Strip `/api/<tenant>` when computing backend URI
- Extract out `getUriPath` for unit testing
- Add unit test
- Update README.md "Testing" make cmd 
PTAL: @mhamann @rabbah

Fix getUriPath logic to ignore API tenant base path

---

Dockerfile
build_config_supervisor.sh

Connected to https://github.com/apache/openwhisk-devtools/issues/322
I can confirm that this fixes the rclone binary, but I haven't tested it against the Docker Compose build that openwhisk-devtools is using, so I can't confirm whether that then works as intended.
I also ensured that the Docker build will fail if rclone can't be installed, which should protect us from this occurring in the future.
Here, rclone actually runs
```
$ docker run apigateway rclone mkdir minio:api-gateway
2020/08/06 21:36:28 Failed to create file system for "minio:api-gateway": didn't find section in config file
```

fix(rclone): use official install mechanism

---

conf.d/managed_endpoints.conf

Updating parsing for $gatewayPath in allow for trailing non-alphanumeric characters in path parameters.

Allow trailing non-alphanumeric character in path params
