api-gateway-config/scripts/lua/routing.lua
Fixed typo
@mhamann @alexsong93 PTAL
=> fix typo in PATCH

api-gateway-config/scripts/lua/lib/filemgmt.lua, api-gateway-config/scripts/lua/lib/request.lua
Closes #5. @mhamann @DavidMGreen PTAL
=> Add CORS headers to nginx conf file

api-gateway-config/scripts/lua/routing.lua
Fix spacing
@mhamann @alexsong93 PTAL
=> fix spacing from 4 to 2

README.md, api-gateway-config/scripts/lua/lib/filemgmt.lua, api-gateway-config/scripts/lua/lib/utils.lua, api-gateway-config/scripts/lua/policies/mapping.lua, api-gateway-config/scripts/lua/routing.lua
From @DavidMGreen:
> Added a default option for body, query and header parameters
> fixes: #46
> @cmwalker @alexsong93 PTAL
=> Adding a default action to the mapping policy

api-gateway-config/conf.d/management_apis.conf, api-gateway-config/scripts/lua/lib/filemgmt.lua, api-gateway-config/scripts/lua/lib/redis.lua, api-gateway-config/scripts/lua/lib/utils.lua, api-gateway-config/scripts/lua/management.lua, api-gateway-config/scripts/lua/routing.lua, api-gateway-config/tests/spec/test.lua
#Modify the management interface to match that of `gateway-director-management-interface`, including `/APIs` and `/Tenants`. @mhamann @lostinthestory PTAL. Closes #4
=> Mgmt update

README.md, doc/policies.md, doc/routes.md
Closes #13. Updated the README and created a `doc` folder for the management API/policies definitions. @lostinthestory @DavidMGreen PTAL.
=> Update readme and documentation

.gitignore, api-gateway-config/tests/install-deps.sh, api-gateway-config/tests/run-tests.sh, api-gateway-config/tests/spec/test.lua, concourse/pipeline.yml, concourse/tasks/run-unit-tests.sh, concourse/tasks/run-unit-tests.yml
Added Concourse CI pipeline for running unit tests for pull requests. @mhamann @lostinthestory @DavidMGreen PTAL.
=> Add Concourse CI PR pipeline

api-gateway-config/scripts/lua/lib/redis.lua
Added logic in the subscribe function to reload nginx only if >1 second has passed since last nginx reload. Fixes #26. @mhamann @lostinthestory @DavidMGreen PTAL
=> Add delay between nginx reloads

api-gateway-config/conf.d/managed_endpoints.conf
=> Don't show managed gateway msg when missing API

api-gateway-config/conf.d/managed_endpoints.conf
=> Add proxy for health-check from port 8080 to 9000

Makefile, api-gateway-config/api-gateway.conf, api-gateway-config/conf.d/commons/common-headers.conf, api-gateway-config/scripts/lua/management.lua
Fixes #35 @lostinthestory PTAL
=> Add host and port env variables to common-headers. Update redis timeouts

api-gateway-config/scripts/lua/lib/redis.lua, api-gateway-config/scripts/lua/management.lua
Fixes #38 @lostinthestory PTAL
=> Add checks for illegal single quotes

api-gateway-config/conf.d/managed_endpoints.conf
=> Add X-Gateway-Host header to /50x location block

README.md, api-gateway-config/conf.d/managed_endpoints.conf, api-gateway-config/scripts/lua/lib/redis.lua, api-gateway-config/scripts/lua/lib/utils.lua, api-gateway-config/scripts/lua/management.lua, api-gateway-config/scripts/lua/policies/mapping.lua, api-gateway-config/scripts/lua/routing.lua, doc/routes.md, init.sh
Fixes #45. Also refactored the management interface. @mhamann @DavidMGreen PTAL
=> Get resources directly from redis without conf files

api-gateway-config/api-gateway.conf
=> Increase in-memory buffer size

api-gateway-config/scripts/lua/management.lua, init.sh
Fixes #65. @lostinthestory @mhamann PTAL
=> Fix cpu issue when gateway starts up

api-gateway-config/scripts/lua/policies/security.lua, api-gateway-config/scripts/lua/policies/security/apikey.lua, api-gateway-config/scripts/lua/routing.lua
=> Modularize security policy

api-gateway-config/scripts/lua/management/apis.lua, api-gateway-config/scripts/lua/management/tenants.lua
Fixes #59 this might be controversial.. Comments are welcome
=> fix empty array issue

api-gateway-config/scripts/lua/management/apis.lua, api-gateway-config/scripts/lua/management/tenants.lua
Fixes additional issue with filtering found in #59. Also fixes a typo.
=> Fix empty array issue with filtering

api-gateway-config/conf.d/api_gateway_logging.conf, api-gateway-config/conf.d/managed_endpoints.conf, api-gateway-config/conf.d/management_apis.conf, api-gateway-config/scripts/lua/routing.lua
@mhamann @codymwalker PTAL. Added `tenantId` to access log when a managed API is invoked.
=> Add namespace to access log

api-gateway-config/conf.d/api_gateway_logging.conf, api-gateway-config/conf.d/managed_endpoints.conf, api-gateway-config/scripts/lua/routing.lua
Fixes #96. @codymwalker @mhamann PTAL
=> use tenantId for logging

api-gateway-config/conf.d/api_gateway_logging.conf, api-gateway-config/scripts/lua/lib/redis.lua, api-gateway-config/scripts/lua/routing.lua
=> Handle backendURLs without protocol

scripts/lua/policies/backendRouting.lua
Fixes #124 @codymwalker @mhamann PTAL
=> Fix proxying query parameters

.travis.yml, tools/travis/build.sh, tools/travis/setup.sh
=> add openwhisk travis integration

conf.d/api_gateway_logging.conf, conf.d/managed_endpoints.conf, scripts/lua/policies/rateLimit.lua, scripts/lua/routing.lua
=> Add apiId to access logs

tools/travis/build.sh
Work in progress depends on https://github.com/openwhisk/openwhisk/pull/1984
=> build docker image locally for travis

conf.d/api_gateway_logging.conf
=> Break up request log message

scripts/lua/management/routes/apis.lua
Fixes #147. @codymwalker @DavidMGreen PTAL
=> Tweak v2 output field names

conf.d/api_gateway_logging.conf, conf.d/managed_endpoints.conf, scripts/lua/policies/security/apiKey.lua
Adds `apiKey` value to access logs, if it is defined. If no api key is used, this field will be blank. @mhamann @codymwalker PTAL
=> Log api key to access log

conf.d/managed_endpoints.conf
=> Enable passing server name through TLS SNI

scripts/lua/routing.lua
@taylorking @gclyne PTAL
Now if there is an exact match, it uses that key from redis. Otherwise, it goes through the path param/proxy lookup algorithm.
=> Implement better routing for exact gatewaypath match

scripts/lua/lib/redis.lua, scripts/lua/policies/backendRouting.lua, scripts/lua/routing.lua, tests/fakengx.lua
=> Add x-cf-forwarded-url routing

conf.d/api_gateway_logging.conf, conf.d/managed_endpoints.conf, scripts/lua/routing.lua
Add `analyticsUri` field to access logs, and also set `apiKey` as `-` by default
@codymwalker PTAL
=> Add logging for analytics

scripts/lua/policies/backendRouting.lua, scripts/lua/routing.lua
Fixes the `Failed to validate Route Service Signature` issue with cf apps with multiple routes
=> Fix routing logic for cf apps

scripts/lua/routing.lua
@codymwalker @mhamann PTAL
For cf, for default swagger with the catchall operations, use `redisKey` with just the base path.  Otherwise, use `cfRedisKey` which uses the path from `x-cf-forwarded-url`
=> Fix routing for cf default swagger

scripts/lua/management/routes/tenants.lua
Fixes https://github.com/openwhisk/openwhisk-apigateway/issues/153
=> Update return value for tenant apis

scripts/lua/policies/security/clientSecret.lua, scripts/lua/routing.lua
=> Log updated request headers and redact secrets

scripts/lua/routing.lua
Fixes #175 @codymwalker @mhamann PTAL
=> Fix cf query string

scripts/lua/management/lib/swagger.lua, tests/scripts/lua/management/lib/swagger.lua
=> Fix cors in v2 management interface

doc/v2/management_interface_v2.md, scripts/lua/management/lib/swagger.lua, scripts/lua/policies/rateLimit.lua, scripts/lua/routing.lua
Fixes #192 @codymwalker @mhamann PTAL
=> Fix rate limit interval

scripts/lua/oauth/facebook.lua, scripts/lua/oauth/github.lua, scripts/lua/oauth/google.lua
Realized I was closing redis twice and this was causing weird behavior.
=> fix double close causing redis to sometimes fail before keepalive

.travis.yml, README.md, tools/travis/deploy.sh
=> update readme travis badge

doc/v2/management_interface_v2.md, tests/scripts/lua/management/examples/example1.json, tests/scripts/lua/management/examples/example2.json
@mhamann @taylorking Fixed example swagger for the v2 interface in the docs.
=> Fix example swagger for v2 interface

tools/travis/build.sh
=> adding more apigateway tests

scripts/lua/policies/backendRouting.lua
Fixes #224 @codymwalker @mhamann PTAL
=> Concatenate query params from dynamic backend

scripts/lua/policies/security/apiKey.lua, scripts/lua/policies/security/clientSecret.lua, tests/scripts/lua/security.lua
=> apiKey and ClientID in query string

doc/profiling.md, scripts/lua/api_gateway_init.lua, scripts/lua/cors.lua, scripts/lua/lib/dataStore.lua, scripts/lua/lib/logger.lua, scripts/lua/lib/redis.lua, scripts/lua/lib/request.lua, scripts/lua/lib/utils.lua, scripts/lua/management/lib/apis.lua, scripts/lua/management/lib/resources.lua, scripts/lua/management/lib/subscriptions.lua, scripts/lua/management/lib/swagger.lua, scripts/lua/management/lib/tenants.lua, scripts/lua/management/lib/validation.lua, scripts/lua/management/routes/apis.lua, scripts/lua/management/routes/subscriptions.lua, scripts/lua/management/routes/tenants.lua, scripts/lua/oauth/appid.lua, scripts/lua/oauth/facebook.lua, scripts/lua/oauth/github.lua, scripts/lua/oauth/google.lua, scripts/lua/oauth/mock.lua, scripts/lua/policies/backendRouting.lua, scripts/lua/policies/mapping.lua, scripts/lua/policies/rateLimit.lua, scripts/lua/policies/security.lua, scripts/lua/policies/security/apiKey.lua, scripts/lua/policies/security/clientSecret.lua, scripts/lua/policies/security/oauth2.lua, scripts/lua/routing.lua
Also, fix TABs in profiling.md and remove author tags where found.
=> Add Apache 2 license to all Lua source files.

Dockerfile
=> Remove onbuild commands and force consumers to explicitly add config

Dockerfile
=> Fix dumb-init entrypoint

scripts/lua/cors.lua, tests/scripts/lua/routing.lua, tools/build/scanCode.cfg, tools/travis/build.sh
Fixes https://github.com/apache/incubator-openwhisk-apigateway/issues/254 @mhamann
=> Allow credentials for cors requests

.travis.yml, conf.d/managed_endpoints.conf
=> Allow periods in managed url paths

doc/v2/management_interface_v2.md, scripts/lua/policies/backendRouting.lua, scripts/lua/routing.lua, tools/travis/build.sh
=> Implement request.path for path parameter mapping

scripts/lua/oauth/app-id.lua, scripts/lua/oauth/facebook.lua, scripts/lua/oauth/github.lua, scripts/lua/oauth/google.lua, tests/scripts/lua/security.lua, tools/travis/build.sh
=> Check for expired oauth tokens

scripts/lua/policies/backendRouting.lua
@mhamann Fixes issue where API may fail with multiple queries when using dynamic backends.
=> Fix multiple query parameter issue for dynamic backends

Dockerfile
As part of adding cross-compile to Power, we needed to upgrade to LuaJIT 2.1-beta3 (from a PPC-specific fork).  This LuaJIT version is not compatible with older versions of OpenRESTy, so we also needed to bump the OpenRESTy version, choosing 1.13.6.1, the latest release.
Reviewers, please opine on the impact of the version change -- while all local tests passed, that doesn't necessarily mean the overall implementation will continue to function appropriately -- what's the broader framework for integration testing?
@sudswas
=> OpenRESTy version bump + Power

scripts/lua/routing.lua
=> Add x-forwarded-url to request headers

scripts/lua/lib/utils.lua, scripts/lua/management/lib/swagger.lua, tests/scripts/lua/management/examples/example3.json, tests/scripts/lua/management/lib/swagger.lua
=> Add support for set-variable in operation-switch

NOTICE.md, NOTICE.txt
Update NOTICE file
- change the extension from `md` to `txt`
- add declaration of dependencies.
=> update notice file

DEPENDENCIES.md, Dockerfile, Makefile
=> Add license header to 3 files

tools/travis/setup.sh
=> updated ansible version for travis to 2.5.0

tools/travis/build.sh, tools/travis/setup.sh
=> refactor travis setup

Dockerfile, Makefile, README.md, api-gateway.conf, init.sh
=> Add option to encrypt redis password

init.sh
=> Fix awk command in init.sh generating resolvers.conf file

tools/travis/build.sh
In preparation for a reorg in this PR https://github.com/apache/incubator-openwhisk/pull/3760.
=> Move gateway playbook after openwhisk.

tools/travis/build.sh
Related to https://github.com/apache/incubator-openwhisk/pull/3760#issuecomment-403146249.
=> Add playbook to install package.

scripts/lua/cors.lua
=> Add additional headers to remove when cors is disabled

Dockerfile, Makefile
The OpenRESTy project has done significant work upstream to integrate ARM64 architecture into its offering.  I've adjusted the Dockerfile for apigateway to download and apply updated modules to OpenRESTy to integrate these changes ONLY when the ARM64 architecture is detected.
There's a lot more that could be done to clean up the Dockerfile, including using multi-stage builds, but in the interest of keeping PR size manageable, this is all I'm applying at this time.
=> Integrate upstream Aarch64 changes

scripts/lua/policies/mapping.lua
@mhamann Handles the case when a non-JSON is passed in with other map policies.
=> Decode body only if it is JSON

scripts/lua/lib/redis.lua
Added logic to retry redis queries on failures
@mhamann
=> Add retry logic to redis queries

Dockerfile.test.unit, scripts/lua/oauth/app-id.lua, scripts/lua/oauth/facebook.lua, scripts/lua/oauth/github.lua, scripts/lua/oauth/google.lua, scripts/lua/policies/security/oauth2.lua, tests/install-deps.sh, tests/scripts/lua/security.lua
* Fix App ID caching issue (and add tests to match)
* Improve error messages for all OAuth providers
Resolves https://github.com/apache/openwhisk-apigateway/issues/340
=> OAuth fixes and improvements

init.sh
=> Disable ipv6 during DNS resolution

scripts/lua/policies/mapping.lua
Related to https://github.com/apache/openwhisk-apigateway/pull/324
=> Fix array handling during mapping operations

scripts/lua/management/lib/swagger.lua, tools/travis/build.sh
=> Rename parsePolicies to parseSwaggerPolicies to avoid conflict
